### ISSUE TITLE
Problem with installing packages

### ISSUE THREAD

**Issue by GifperTC** [kidstylex/TELLING#47]
Required packages in requirements.txt are quite a lot, so maybe README file should include an instruction to activate environment before installing the packages. Because those packages are only required at first time installation, if they don’t need to use all those packages afterwards, leaving them permanently maybe unnecessary.

**Comment by GifperTC** [comment]
Also, Big problem here. While downloading the required package, there is an error: PyObjC requires macOS to build. This package requires macOS to build, so Window or Linux users will have a big problem about this. I have a big problem at installing the packages and can't continue, if you can provide some help that would be appreciated.

**Comment by bluaries** [comment]
Because we use 'pip-freeze'. So it'll generate a lot of packages and create our requirements.txt. but for now, we remove some unnecessary from requirements.txt already
